// backup file that contains JSON with skills and related to them jobs. Now all this data in the ext_all_skills and ext_jobs tables. But if you need to fill the table data again and connect skills and jobs (ext_job_skill table), this file and next functions can be used for this: uploadSkills() - to fill ext_all_skills table; createAutoJobs() - to fill ext_jobs table with jobs that are in the file but not yet in the dataset; connectJobsToSkills() - to fill ext_job_skill table to create Many:Many dataset links between skills and their corresponding jobs.

const skillsArray = [
  { skill: ".NET", jobs: ["Software Developer"] },
  { skill: "A/B testing", jobs: ["UI/UX Designer"] },
  { skill: "Accessibility", jobs: ["UI/UX Designer"] },
  { skill: "Active Directory", jobs: ["Technical Support Specialist"] },
  {
    skill: "Agile methodologies",
    jobs: ["Software Developer", "DevOps Engineer", "IT Project Manager"],
  },
  {
    skill: "Android",
    jobs: ["Mobile App Developer", "Technical Support Specialist"],
  },
  { skill: "Angular", jobs: ["Frontend Developer"] },
  { skill: "Ansible", jobs: ["DevOps Engineer"] },
  { skill: "API management", jobs: ["Cloud Architect"] },
  { skill: "Asana", jobs: ["IT Project Manager"] },
  {
    skill: "AWS",
    jobs: ["Backend Developer", "Cloud Architect", "DevOps Engineer"],
  },
  { skill: "AWS RDS", jobs: ["Database Administrator"] },
  {
    skill: "Azure",
    jobs: ["Backend Developer", "Cloud Architect", "DevOps Engineer"],
  },
  { skill: "Azure SQL Database", jobs: ["Database Administrator"] },
  { skill: "Babel", jobs: ["Frontend Developer"] },
  { skill: "Backup and recovery", jobs: ["Technical Support Specialist"] },
  { skill: "Bayesian statistics", jobs: ["Data Scientist"] },
  { skill: "Big data", jobs: ["Data Scientist"] },
  { skill: "Bitcoin", jobs: ["Blockchain Developer"] },
  { skill: "Bitcoin Script", jobs: ["Blockchain Developer"] },
  { skill: "Blockchain fundamentals", jobs: ["Blockchain Developer"] },
  { skill: "BGP", jobs: ["Network Engineer"] },
  { skill: "Budget management", jobs: ["IT Project Manager"] },
  {
    skill: "Business continuity",
    jobs: ["Information Security Analyst", "IT Manager/CIO"],
  },
  { skill: "Business intelligence", jobs: ["Data Analyst", "IT Manager/CIO"] },
  { skill: "C", jobs: ["Software Developer"] },
  { skill: "C++", jobs: ["Software Developer"] },
  { skill: "C#", jobs: ["Software Developer"] },
  { skill: "Cassandra", jobs: ["Database Administrator"] },
  {
    skill: "Caffe",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  {
    skill: "Change management",
    jobs: ["IT Project Manager", "IT Manager/CIO"],
  },
  { skill: "Chaincode", jobs: ["Blockchain Developer"] },
  { skill: "Chef", jobs: ["DevOps Engineer"] },
  { skill: "Cisco IOS", jobs: ["Network Engineer"] },
  { skill: "CircleCI", jobs: ["DevOps Engineer"] },
  { skill: "Cloud computing architecture", jobs: ["Cloud Architect"] },
  { skill: "Cloud cost optimization", jobs: ["Cloud Architect"] },
  { skill: "Cloud migration", jobs: ["Cloud Architect"] },
  { skill: "Cloud monitoring", jobs: ["Cloud Architect"] },
  { skill: "Cloud-native development", jobs: ["Cloud Architect"] },
  { skill: "Cloud performance optimization", jobs: ["Cloud Architect"] },
  { skill: "Cloud security", jobs: ["Cloud Architect"] },
  { skill: "Cloud storage", jobs: ["Cloud Architect"] },
  { skill: "COBIT", jobs: ["IT Manager/CIO"] },
  { skill: "Code review", jobs: ["Software Developer"] },
  { skill: "Communication skills", jobs: ["IT Project Manager"] },
  {
    skill: "Computer vision",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "Configuration management", jobs: ["DevOps Engineer"] },
  { skill: "Consensus algorithms", jobs: ["Blockchain Developer"] },
  { skill: "Containers", jobs: ["DevOps Engineer"] },
  { skill: "Continuous deployment", jobs: ["DevOps Engineer"] },
  { skill: "Continuous integration", jobs: ["DevOps Engineer"] },
  {
    skill: "Convolutional neural networks",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  {
    skill: "CNN",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "Couchbase", jobs: ["Database Administrator"] },
  {
    skill: "Cryptography",
    jobs: ["Blockchain Developer", "Information Security Analyst"],
  },
  { skill: "CSS", jobs: ["UI/UX Designer", "Frontend Developer"] },
  { skill: "CSS3", jobs: ["Frontend Developer"] },
  { skill: "Customer service", jobs: ["Technical Support Specialist"] },
  { skill: "Data center management", jobs: ["IT Manager/CIO"] },
  { skill: "Data integration", jobs: ["Data Engineer"] },
  { skill: "Data modeling", jobs: ["Data Engineer"] },
  { skill: "Data pipeline design", jobs: ["Data Engineer"] },
  { skill: "Data quality", jobs: ["Data Analyst"] },
  { skill: "Data visualization", jobs: ["Data Analyst", "Data Scientist"] },
  { skill: "Data warehousing", jobs: ["Data Engineer"] },
  { skill: "Database design", jobs: ["Database Administrator"] },
  { skill: "Database monitoring", jobs: ["Database Administrator"] },
  { skill: "Database security", jobs: ["Database Administrator"] },
  { skill: "Decentralized storage", jobs: ["Blockchain Developer"] },
  {
    skill: "Deep learning",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "Design systems", jobs: ["UI/UX Designer"] },
  { skill: "DevOps", jobs: ["DevOps Engineer"] },
  { skill: "DHCP", jobs: ["Technical Support Specialist", "Network Engineer"] },
  { skill: "Digital forensics", jobs: ["Information Security Analyst"] },
  { skill: "Disaster recovery", jobs: ["IT Manager/CIO"] },
  { skill: "Django", jobs: ["Backend Developer"] },
  { skill: "DNS", jobs: ["Technical Support Specialist", "Network Engineer"] },
  { skill: "Docker", jobs: ["Backend Developer", "DevOps Engineer"] },
  { skill: "Domain-driven design", jobs: ["Software Developer"] },
  { skill: "DDD", jobs: ["Software Developer"] },
  { skill: "dApp development", jobs: ["Blockchain Developer"] },
  { skill: "EIGRP", jobs: ["Network Engineer"] },
  { skill: "ELK Stack", jobs: ["Backend Developer"] },
  { skill: "Encryption", jobs: ["Information Security Analyst"] },
  {
    skill: "Endpoint security",
    jobs: ["Technical Support Specialist", "Information Security Analyst"],
  },
  { skill: "Enterprise architecture", jobs: ["IT Manager/CIO"] },
  { skill: "ETL", jobs: ["Data Engineer"] },
  { skill: "Ethereum", jobs: ["Blockchain Developer"] },
  { skill: "Ethical hacking", jobs: ["Information Security Analyst"] },
  { skill: "Express.js", jobs: ["Backend Developer"] },
  { skill: "Figma", jobs: ["UI/UX Designer"] },
  {
    skill: "Firewalls",
    jobs: [
      "Technical Support Specialist",
      "Information Security Analyst",
      "Network Engineer",
    ],
  },
  { skill: "Flask", jobs: ["Backend Developer"] },
  { skill: "Flink", jobs: ["Data Engineer"] },
  { skill: "Gantt charts", jobs: ["IT Project Manager"] },
  {
    skill: "GCP",
    jobs: ["Backend Developer", "Cloud Architect", "DevOps Engineer"],
  },
  { skill: "GCP Cloud SQL", jobs: ["Database Administrator"] },
  { skill: "GDPR", jobs: ["IT Manager/CIO"] },
  {
    skill: "Generative adversarial networks",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  {
    skill: "GAN",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  {
    skill: "Git",
    jobs: [
      "Software Developer",
      "UI/UX Designer",
      "Frontend Developer",
      "Backend Developer",
      "DevOps Engineer",
    ],
  },
  { skill: "Grafana", jobs: ["Backend Developer"] },
  { skill: "Graphic design", jobs: ["UI/UX Designer"] },
  { skill: "Gulp", jobs: ["Frontend Developer"] },
  { skill: "Hadoop", jobs: ["Data Engineer"] },
  { skill: "HBase", jobs: ["Data Engineer"] },
  { skill: "High availability", jobs: ["Database Administrator"] },
  { skill: "HIPAA", jobs: ["IT Manager/CIO"] },
  { skill: "Hive", jobs: ["Data Engineer"] },
  { skill: "HTML5", jobs: ["UI/UX Designer", "Frontend Developer"] },
  { skill: "Hybrid cloud", jobs: ["Cloud Architect"] },
  { skill: "Hyperledger Composer", jobs: ["Blockchain Developer"] },
  { skill: "Hyperledger Fabric", jobs: ["Blockchain Developer"] },
  { skill: "IBM Db2", jobs: ["Database Administrator"] },
  { skill: "ICO", jobs: ["Blockchain Developer"] },
  { skill: "IEO", jobs: ["Blockchain Developer"] },
  { skill: "STO", jobs: ["Blockchain Developer"] },
  {
    skill: "Identity and access management",
    jobs: ["Information Security Analyst"],
  },
  { skill: "Incident management", jobs: ["Information Security Analyst"] },
  { skill: "Incident response", jobs: ["Information Security Analyst"] },
  { skill: "Indexing", jobs: ["Database Administrator"] },
  { skill: "Infrastructure as code", jobs: ["DevOps Engineer"] },
  { skill: "Information architecture", jobs: ["UI/UX Designer"] },
  { skill: "Interaction design", jobs: ["UI/UX Designer"] },
  { skill: "Intrusion detection", jobs: ["Information Security Analyst"] },
  { skill: "Intrusion prevention", jobs: ["Information Security Analyst"] },
  {
    skill: "iOS",
    jobs: ["Mobile App Developer", "Technical Support Specialist"],
  },
  { skill: "IP addressing and subnetting", jobs: ["Network Engineer"] },
  { skill: "IPFS", jobs: ["Blockchain Developer"] },
  { skill: "IPv4 and IPv6", jobs: ["Network Engineer"] },
  { skill: "ISO 27001", jobs: ["IT Manager/CIO"] },
  { skill: "IT architecture", jobs: ["IT Manager/CIO"] },
  { skill: "IT budgeting", jobs: ["IT Manager/CIO"] },
  { skill: "IT governance", jobs: ["IT Manager/CIO"] },
  { skill: "IT strategy", jobs: ["IT Manager/CIO"] },
  { skill: "ITIL", jobs: ["IT Manager/CIO"] },
  { skill: "Java", jobs: ["Software Developer", "Mobile App Developer"] },
  { skill: "JavaScript", jobs: ["Software Developer", "Frontend Developer"] },
  { skill: "Jenkins", jobs: ["DevOps Engineer"] },
  { skill: "Jira", jobs: ["IT Project Manager"] },
  { skill: "jQuery", jobs: ["Frontend Developer"] },
  { skill: "JSON", jobs: ["Frontend Developer", "Backend Developer"] },
  { skill: "Kafka", jobs: ["Data Engineer"] },
  {
    skill: "Keras",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "Kubernetes", jobs: ["Backend Developer", "DevOps Engineer"] },
  { skill: "Laravel", jobs: ["Backend Developer"] },
  {
    skill: "Linux",
    jobs: [
      "Technical Support Specialist",
      "Backend Developer",
      "DevOps Engineer",
    ],
  },
  { skill: "Load balancing", jobs: ["Network Engineer"] },
  {
    skill: "Machine learning",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "MariaDB", jobs: ["Database Administrator"] },
  { skill: "Meraki", jobs: ["Network Engineer"] },
  { skill: "Microsoft Project", jobs: ["IT Project Manager"] },
  { skill: "MongoDB", jobs: ["Database Administrator"] },
  { skill: "MySQL", jobs: ["Database Administrator"] },
  {
    skill: "Natural language processing",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  {
    skill: "NLP",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "Network design", jobs: ["Network Engineer"] },
  { skill: "Network monitoring", jobs: ["Network Engineer"] },
  { skill: "Network security", jobs: ["Network Engineer"] },
  { skill: "Network troubleshooting", jobs: ["Network Engineer"] },
  { skill: "Next.js", jobs: ["Frontend Developer"] },
  { skill: "Node.js", jobs: ["Backend Developer"] },
  { skill: "NoSQL", jobs: ["Database Administrator"] },
  { skill: "NPM", jobs: ["Frontend Developer"] },
  { skill: "Objective-C", jobs: ["Mobile App Developer"] },
  { skill: "Oracle", jobs: ["Database Administrator"] },
  { skill: "PCI DSS", jobs: ["IT Manager/CIO"] },
  { skill: "Penetration testing", jobs: ["Information Security Analyst"] },
  { skill: "Photoshop", jobs: ["UI/UX Designer"] },
  { skill: "Pig", jobs: ["Data Engineer"] },
  { skill: "PostgreSQL", jobs: ["Database Administrator"] },
  { skill: "Power BI", jobs: ["Data Analyst"] },
  { skill: "PRINCE2", jobs: ["IT Project Manager"] },
  { skill: "Product management", jobs: ["IT Manager/CIO"] },
  { skill: "Project management", jobs: ["IT Project Manager"] },
  { skill: "Project scheduling", jobs: ["IT Project Manager"] },
  { skill: "Prototype design", jobs: ["UI/UX Designer"] },
  {
    skill: "Python",
    jobs: [
      "Software Developer",
      "Data Scientist",
      "Artificial Intelligence/Machine Learning Engineer",
    ],
  },
  {
    skill: "Quality assurance",
    jobs: ["Software Developer", "IT Project Manager"],
  },
  { skill: "React", jobs: ["Frontend Developer"] },
  { skill: "React Native", jobs: ["Mobile App Developer"] },
  { skill: "Redux", jobs: ["Frontend Developer"] },
  { skill: "Regulatory compliance", jobs: ["IT Manager/CIO"] },
  {
    skill: "Reinforcement learning",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "Relational databases", jobs: ["Database Administrator"] },
  { skill: "Remote work management", jobs: ["IT Manager/CIO"] },
  { skill: "REST", jobs: ["Backend Developer"] },
  { skill: "Responsive design", jobs: ["UI/UX Designer"] },
  {
    skill: "Risk assessment",
    jobs: ["Information Security Analyst", "IT Manager/CIO"],
  },
  { skill: "Risk management", jobs: ["IT Project Manager", "IT Manager/CIO"] },
  { skill: "Ruby", jobs: ["Backend Developer"] },
  { skill: "Ruby on Rails", jobs: ["Backend Developer"] },
  { skill: "SAP", jobs: ["Database Administrator"] },
  { skill: "SAS", jobs: ["Data Analyst"] },
  { skill: "Scala", jobs: ["Software Developer"] },
  { skill: "Scrum", jobs: ["IT Project Manager"] },
  { skill: "Security architecture", jobs: ["Information Security Analyst"] },
  { skill: "Security audit", jobs: ["Information Security Analyst"] },
  {
    skill: "Security policies",
    jobs: ["Information Security Analyst", "IT Manager/CIO"],
  },
  { skill: "SEO", jobs: ["UI/UX Designer"] },
  { skill: "Server administration", jobs: ["Technical Support Specialist"] },
  { skill: "Serverless architecture", jobs: ["Cloud Architect"] },
  { skill: "SharePoint", jobs: ["Technical Support Specialist"] },
  { skill: "Sketch", jobs: ["UI/UX Designer"] },
  { skill: "Smart contracts", jobs: ["Blockchain Developer"] },
  { skill: "Smarty", jobs: ["Frontend Developer"] },
  { skill: "Solidity", jobs: ["Blockchain Developer"] },
  { skill: "Spark", jobs: ["Data Engineer"] },
  {
    skill: "SQL",
    jobs: ["Database Administrator", "Data Analyst", "Data Engineer"],
  },
  { skill: "SQLite", jobs: ["Database Administrator"] },
  {
    skill: "SSL/TLS",
    jobs: ["Technical Support Specialist", "Information Security Analyst"],
  },
  { skill: "Storybook", jobs: ["Frontend Developer"] },
  { skill: "Strategic planning", jobs: ["IT Manager/CIO"] },
  { skill: "Swift", jobs: ["Mobile App Developer"] },
  { skill: "Tableau", jobs: ["Data Analyst"] },
  { skill: "TCP/IP", jobs: ["Network Engineer"] },
  {
    skill: "TensorFlow",
    jobs: ["Artificial Intelligence/Machine Learning Engineer"],
  },
  { skill: "Test-driven development", jobs: ["Software Developer"] },
  { skill: "TDD", jobs: ["Software Developer"] },
  { skill: "TypeScript", jobs: ["Frontend Developer"] },
  { skill: "UI design", jobs: ["UI/UX Designer"] },
  { skill: "UX design", jobs: ["UI/UX Designer"] },
  { skill: "Vendor management", jobs: ["IT Manager/CIO"] },
  { skill: "Virtualization", jobs: ["Technical Support Specialist"] },
  { skill: "Visual design", jobs: ["UI/UX Designer"] },
  { skill: "VMware", jobs: ["Technical Support Specialist"] },
  { skill: "Vue.js", jobs: ["Frontend Developer"] },
  { skill: "Web design", jobs: ["UI/UX Designer"] },
  {
    skill: "Web development",
    jobs: ["Frontend Developer", "Backend Developer"],
  },
  { skill: "Webpack", jobs: ["Frontend Developer"] },
  { skill: "Windows", jobs: ["Technical Support Specialist"] },
  { skill: "Wireframing", jobs: ["UI/UX Designer"] },
  { skill: "WordPress", jobs: ["Frontend Developer"] },
  { skill: "XML", jobs: ["Frontend Developer", "Backend Developer"] },
  { skill: "Yarn", jobs: ["Frontend Developer"] },
  { skill: "Yii", jobs: ["Backend Developer"] },
  { skill: "Zend Framework", jobs: ["Backend Developer"] },
  { skill: "Zero trust security", jobs: ["Information Security Analyst"] },
  { skill: "ZigBee", jobs: ["IoT Developer"] },
  { skill: "Zookeeper", jobs: ["Data Engineer"] },
  { skill: "Hospitality finance", jobs: ["CY"] },
  { skill: "Portfolio management", jobs: ["CY"] },
  { skill: "Asset management", jobs: ["CY"] },
  { skill: "Mergers & Acquisitions (M&A)", jobs: ["CY"] },
  { skill: "Acquisitions", jobs: ["CY"] },
  { skill: "Hospitality", jobs: ["CY"] },
  { skill: "Real Estate Private Equity", jobs: ["CY"] },
  { skill: "Hotel Management", jobs: ["CY"] },
  { skill: "Hospitality Consulting", jobs: ["CY"] },
  { skill: "Hospitality Law", jobs: ["CY"] },
  { skill: "Real Estate Acquisition", jobs: ["CY"] },
  { skill: "Commercial Real Estate Acquisition", jobs: ["CY"] },
  { skill: "Investments in Hospitality", jobs: ["CY"] },
  { skill: "Hospitality Investments", jobs: ["CY"] },
];

module.exports = skillsArray;





